### PR TITLE
feat: polish balance page

### LINKED ISSUE #1352: [Task]: Polish balance section in address page
### Task description

Polish this section so it looks better than it does now
image
We can discuss about it, we could even ask the designers, but imo we can get to something decent by reorganizing a bit the section

### PR DESCRIPTION
**Pull request by panteleymonchuk**
# Description of change

Closes #1352

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Take a look address page.

Desktop
image

Tablet
image

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by brancoder — COMMENTED** [review]
Should we remove the empty Conditionally locked mana panel?

image

**Review by brancoder — CHANGES_REQUESTED** [review]
Resolve conflicts please :pray:

**Comment by brancoder** [comment]
@panteleymonchuk  There's something weird with storage deposit on this address `rms1qrmc0qhqadnsm0nefxunnhtexsrgqr6wa3aest640q4a4t0lcruj5ff7wa7`
image

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
2 extra small details
- We should unify showing always unit when 0 or not so we avoid these situations 
image
- The copy feature could be improved so you always copy the "raw amount", the syll amount in the subunit unit, without the ticker, so you copy the full value number, and not a string, eg if the balance is 1.123 TST the value copied should be `1123000` instead of `1.123 TST`

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
As commented in slack, lets detatch the unit toggles from different boxes

**Review by brancoder — APPROVED** [review]
LGTM

**Pull request merged**
