### PR TITLE
Fix: GitHub workflows updated to latest node and npm versions

### PR DESCRIPTION
**Pull request by abbasabid**
# Description of change

- Updated shimmer client staging workflow to use Node version 16.16.
- Updated shimmer client staging workflow to use Npm version 8.18.
- Updated shimmer api staging workflow to use Node version 16.16.
- Updated shimmer api staging workflow to use Npm version 8.18.

Aims to fix https://github.com/iotaledger/explorer/issues/490

## Type of change

- Enhancement (a non-breaking change which adds functionality)

### CODE REVIEW

**Comment by msarcev** [comment]
Looks good. We need to do the same thing for the prod configs. And we can update also mainnet staging and prod workflow on stardust branch while we are at it.

**Comment by abbasabid** [comment]
> Looks good. We need to do the same thing for the prod configs. And we can update also mainnet staging and prod workflow on stardust branch while we are at it.

Done.

**Comment by msarcev** [comment]
LGTM.
Please, since we also updated "bot", make sure to check that it works locally with `v16.16`.

**Comment by abbasabid** [comment]
> LGTM. Please, since we also updated "bot", make sure to check that it works locally with `v16.16`.

I did `npm i` on `discord-bot` and it is working fine.

**Review by msarcev — APPROVED** [review]

**Pull request merged**
