### PR TITLE
feat: Show Explorer client version from package.json on the Footer

### PR DESCRIPTION
**Pull request by msarcev**
# Description of change

- Injected the Explorer client version for package.json in frontend (footer)

Resolves https://github.com/iotaledger/explorer/issues/967

## Type of change

- Enhancement (a non-breaking change which adds functionality)

### CODE REVIEW

**Comment by msarcev** [comment]
With this the client version will be shown in the page footer like so:
image

but we are open for suggestions for a better "placement" if required :D

**Comment by msarcev** [comment]
Suggested placement is something like this
image

**Review by VmMad — APPROVED** [review]
lgtm

**Review by msarcev — COMMENTED** [review]
LGTM 👍🏻

**Pull request merged**
